server:
  port: 8089

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/clientes/**

        - id: reserva-service
          uri: lb://reserva-service
          predicates:
            - Path=/api/reservas/**

        - id: historial-service
          uri: lb://historial-service
          predicates:
            - Path=/api/historial/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

info:
  app:
    name: API Gateway
    version: 1.0