server:
  port: 8083

spring:
  application:
    name: historial-service

  datasource:
    url: jdbc:mysql://mysql-historial:3306/historial_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  info:
    env:
      enabled: true

app:
  messages:
    error-service: "No fue posible consultar el servicio. Intente nuevamente."

info:
  app:
    name: Historial Service
    version: 1.0

resilience4j:
  circuitbreaker:
    instances:
      reservaService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      reservaService:
        maxAttempts: 3
        waitDuration: 2s